version: "3.8"

services:
#  client:
#    image: infratestclient
#  server:
#    image: infratestserver
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  db-data:
