version: "3.8"

services:
  client:
    image: infratestclient
    restart: always
    build: ./client
    depends_on:
      - server
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:3030"
    ports:
      - "3000:3000"
  server:
    image: infratestserver
    build: ./server
    depends_on:
      - db
      - redis
    environment:
      TYPEORM_HOST: db
      TYPEORM_USERNAME: pguser
      TYPEORM_PASSWORD: pgpass
      TYPEORM_DATABASE: pgdb
      TYPEORM_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      PORT: 3030
    ports:
      - "3030:3030"
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  db-data:
