on:
  push:

jobs:
  build-server-image:
    name: Build server image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-region: "${{ secrets.AWS_REGION }}"
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          role-duration-seconds: 1200
          role-session-name: "temp-session"
          role-skip-session-tagging: true

      - name: Docker login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: infratestserver:latest
          secrets: GIT_AUTH_TOKEN=${{ github.token }}
